### ISSUE TITLE
CreateRootlessEnvironment  needs path changes and other fixes

### ISSUE THREAD

**Issue by bolangi** [gobolinux/Scripts#20]

**Comment by hishamhm** [comment]
CreateRootlessEnvironment is no longer included in the Scripts package.

**Comment by bolangi** [comment]
Fair enough. I'm closing this ticket.

**Comment by bolangi** [comment]
Rootless is mentioned significantly in both gobolinux.org and the wiki.According to [Sandboxing under gobolinux](https://github.com/gobolinux/Documentation/wiki/Sandboxing-under-GoboLinux),  

> FiboSandbox is the sandbox installer for GoboLinux Rootless.

I heard that that gobo environment was first prototyped in a rootless configuration, and that it is sufficient to  demonstrate the system of program management using symlinks and the entire software development toolchain. 

Perhaps there was concern that people will be disappointed by the lack of features in a rootless installation compared to the full root installation. Perhaps there were support problems. 

Regardless of the reason, if GoboLinux policy is not to support Rootless, references to Rootless in the website (and wiki) could be reviewed and changed where necessary to reflect this.

Speaking to Lucas on IRC, I got the impression that gobo rootless was an important component and illustration of the system, and a configuration that he also uses.  I think that it could be reasonably supplied  outside the Scripts package. 

I am reopening the issue for  opinions on the place of rootless in the documentation at gobolinux.org and the wiki, and whether we should indicate that rootless is not part of gobolinux's current offerings.

**Comment by hishamhm** [comment]
> FiboSandbox is the sandbox installer for GoboLinux Rootless.

I don't think this is true, because regular users running Rootless cannot sudo into the Fibo user. A user with superuser privileges could use Fibo, but that was never the common scenario. Most commonly, Rootless was used without sandboxing. FiboSandbox is the older sandbox mechanism which is used as a fallback when unionfs is not available.

> I heard that that gobo environment was first prototyped in a rootless configuration, and that it is sufficient to demonstrate the system of program management using symlinks and the entire software development toolchain.

It was so during the original inception of GoboLinux, but Compile didn't exist back then. While Compile does run on a rootless setup, not all recipes are compatible with it: some by definition — it doesn't make sense to run an init system on rootless; some by accident because the upstream authors assume the program will be installed and used system-wide. The end result is that the end-user experience for Compile in Rootless is incomplete.

> Perhaps there was concern that people will be disappointed by the lack of features in a rootless installation compared to the full root installation. Perhaps there were support problems.

True in both accounts. Another major cause for dropping Rootless was that it makes maintaining the recipes tree a _lot_ harder, because of patches to fix path problems that happen only in Rootless. We are already "understaffed" for maintaining recipes, and Gobo had not seen updates for years, so adding another complicator to the process wasn't helping. Maintaining Rootless is not worth it if it hurts the survival of GoboLinux as a whole (and the health of the recipes tree is a decisive factor for the distro).

Newly built recipes assume that $target=/usr, and that simplifies building packages a _lot_. Many of these recipes are not compatible with Rootless, and we don't check for it. Rootless compatibility in the tree was never 100%, and over the last few years, it must have deteriorated.

> Speaking to Lucas on IRC, I got the impression that gobo rootless was an important component and illustration of the system, and a configuration that he also uses. 

@lucasvr is an outlier (he's an über-power-user and he's been maintaining the distro practically single-handedly for a few years now) so he knows the quirks of Rootless and can work around them. Rootless is the kind of thing we can kind of maintain for ourselves (and that's probably why we haven't removed all internal rootless-specific bits from Scripts) but that it's hard to provide a smooth experience for others (to be honest, it's hard to provide a smooth experience for the main distro already! and we control all variables for that except the user's hardware — imagine making a subset of it work inside other distros working around their own quirks).

> I think that it could be reasonably supplied outside the Scripts package.

That's the point, it can't. Rootless adds a _lot_ of corner cases inside both Scripts and Compile (and, most critically, the recipes). Merely moving the CreateRootlessEnvironment to a separate repo does not move Rootless "outside of Scripts".

Unless one is willing to maintain their own fork of the Scripts, Compile and recipes package, with all the Rootless quirks. At this point, one has reinvented an ad-hoc version of Homebrew. (Which is to say, it is a _lot_ of work.)

> I am reopening the issue for opinions on the place of rootless in the documentation at gobolinux.org and the wiki, and whether we should indicate that rootless is not part of gobolinux's current offerings.

When we transitioned to $target=/usr, we discussed the issue of Rootless, and we agreed that dropping its support would be better and we removed CreateRootlessEnvironment from Scripts. So, I think the documentation should match this decision.

**Comment by bolangi** [comment]
> Newly built recipes assume that $target=/usr, and that simplifies building packages a _lot_. Many of these recipes are not compatible with Rootless, and we don't check for it. Rootless compatibility in the tree was never 100%, and over the last few years, it must have deteriorated.
> 

my scenario, is development purposes, on an existing linux
distro, where I have root privileges, and would be a more
convenient environment than always getting mouse grabbed
in qemu. 

If I use root authority for the sandboxing and possibly
other phases to allow recipes to be compiled in a way closer
to under normal gobo?

Is it possible that having a standard rootless environment
capable of testing recipes would be a source
of information on classes of issues about how to improve the
Compile architecture?

> > Speaking to Lucas on IRC, I got the impression that gobo rootless was an important component and illustration of the system, and a configuration that he also uses. 
> 
> @lucasvr is an outlier (he's an über-power-user and he's been maintaining the distro practically single-handedly for a few years now) so he knows the quirks of Rootless and can work around them. Rootless is the kind of thing we can kind of maintain for ourselves (and that's probably why we haven't removed all internal rootless-specific bits from Scripts) but that it's hard to provide a smooth experience for others (to be honest, it's hard to provide a smooth experience for the main distro already! and we control all variables for that except the user's hardware — imagine making a subset of it work inside other distros working around their own quirks).

> > I think that it could be reasonably supplied outside the Scripts package.
> 
> That's the point, it can't. Rootless adds a _lot_ of corner cases inside both Scripts and Compile (and, most critically, the recipes). Merely moving the CreateRootlessEnvironment to a separate repo does not move Rootless "outside of Scripts".

 
> Unless one is willing to maintain their own fork of the Scripts, Compile and recipes package, with all the Rootless quirks. At this point, one has reinvented an ad-hoc version of Homebrew. (Which is to say, it is a _lot_ of work.)

I could see that it is a different goal than the main thrust
of gobo project development, and therefore a drag. 

> > I am reopening the issue for opinions on the place of rootless in the documentation at gobolinux.org and the wiki, and whether we should indicate that rootless is not part of gobolinux's current offerings.
> 
> When we transitioned to $target=/usr, we discussed the issue of Rootless, and we agreed that dropping its support would be better and we removed CreateRootlessEnvironment from Scripts. So, I think the documentation should match this decision.

Thank you.

-- 
Joel Roth

**Comment by hishamhm** [comment]
> my scenario, is development purposes, on an existing linux distro, where I have root privileges, and would be a more convenient environment than always getting mouse grabbed in qemu. 

You could use VirtualBox with Guest Additions, which does not grab the mouse, or simply launch sshd in the QEMU instance and use a regular local terminal in your host distro and ssh into the VM.

> If I use root authority for the sandboxing and possibly other phases to allow recipes to be compiled in a way closer to under normal gobo?

They would still have mismatching Dependencies and BuildInformation, because dependencies leak from the host system into Rootless-built packages.

> Is it possible that having a standard rootless environment capable of testing recipes would be a source of information on classes of issues about how to improve the Compile architecture?

It would add more moving parts. It goes down to what does it mean to "improve the Compile architecture". Whenever people say that, they usually mean making something more flexible or making it do more stuff. We've been through that phase before. At certain points, Compile was used:

* as a cross-compiler
* running on Rootless
* made to run in Mac OS X
* made to run in Cygwin
* etc.

Nothing of this comes for free. All of it adds code, complexity and corner cases. Recipes got more complicated, going against the initial core goal of Compile, and the very reason why it exists (instead of reusing one of the many build tools). At one point, we decided to scale down and focus on its core competency: building native packages for GoboLinux inside GoboLinux.

>> Unless one is willing to maintain their own fork of the Scripts, Compile and recipes package, with all the Rootless quirks. At this point, one has reinvented an ad-hoc version of Homebrew. (Which is to say, it is a _lot_ of work.)
>
> I could see that it is a different goal than the main thrust
of gobo project development, and therefore a drag. 

Yes, and we already tried that, with the best of our intentions. Unfortunately, it didn't work out.
