### ISSUE TITLE
inconsistent behavior on version resolution by `FindDependencies`

### ISSUE THREAD

**Issue by Nuc1eoN** [gobolinux/Scripts#39]
I have observed some oddities with `FindDependencies` which is being used by `Runner` and thus also by `Compile`.

To follow create the following scenario:

You have a program called `Dummy` under `/Programs` with the following versions:
```bash
ls /Programs/Dummy
1.5 1.6 1.12 1.13
```
You can follow along by recreating this file system structure on your system.

Now create a `Dependencies` file in your home dir with the following content:
```
Dummy > 1.5
```
Now run `FindDependencies` on that file:
```bash
FindDependencies Dependencies
```
The expected result is `1.13` right?
However the actual result is:
```
/Programs/Dummy/1.6
```
Obviously wrong! The first guess here is that `FindDependencies` sees `1.6` > `1.13`, right?
One might _guess_ it is due to the double digits!

However if so, how does the following make any sense:
Now put `Dummy > 1.6` into your `Dependencies` file. Now `FindDependencies` has the following result:
```
/Programs/Dummy/1.13
```
Bollocks! So suddenly `FindDependencies` resolves `1.6` < `1.13`!

I struggle to understand what is going on here.

**Comment by hishamhm** [comment]
I haven't looked at the code, but my _guess_ is that all that FindDependencies reads the `Dummy` directory and returns _some_ entry that matches (reading the directory in filesystem (i.e. random) order), rather than the best one. _If_ that is the case, for detecting whether a dependency is missing or not, that behavior would be sufficient — but for use with Runner, probably not ideal as it would potentially link with older libraries when newer ones are installed.

Some C debugging of FindDependencies.c would explain what's going on.

**Comment by Nuc1eoN** [comment]
>but for use with Runner, probably not ideal as it would potentially link with older libraries when newer ones are installed.

Yes absolutely, especially since Runner is used by Compile internally.

So if you are in installing a new program with Compile, it will potentially link the wrong dependency version in the build process, potentially leading to a failed build.
This is exactly what happened for me and it took me some time and effort to finally nail it down to Runner and eventually `FindDependencies`.

**Comment by lucasvr** [comment]
Yep, that's a bug. I'm pushing a fix now -- thanks for the heads up!

**Comment by Nuc1eoN** [comment]
@lucasvr Thanks a lot, that fixed it!

PS: Please look into irc chat in case you have forgot. I have sent you a message (10 days ago^^).
